name: Publicar página web

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Preparar archivos de la página
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Publicar en GitHub Pages
        uses: actions/deploy-pages@v4